trello/api-docs

app/templates/power-ups/topics.html
With the latest changes to the power-up.js library we
added a new, simpler way to complete an oauth flow from
within a Power-Up. This change documents that as the
primary authorization solution.
=> Update Power-Ups authorize topic with simpler option

app/templates/docs/card.html
Adds a list of supported values as well as a note about behavior
=> Improve keepFromSource arg docs

app/templates/docs/batch.html
Had a question come in about batch. Thought I'd add a sprinkling of text here.
Lots of white space changes (Thanks HTMLPrettify!). Bulk of relevant additions are here:
- https://github.com/trello/api-docs/pull/44/files#diff-8b80d5ff0a2b2024a01d52248b3b4d96R5
- https://github.com/trello/api-docs/pull/44/files#diff-8b80d5ff0a2b2024a01d52248b3b4d96R20
=> Adding Better Batch Docs

app/scripts/app.js, app/templates/apis/submit-your-app.html, app/templates/power-ups.html, app/templates/power-ups/guidelines.html
Provide a set of guidelines for developers building Power-Ups.
=> Power-Up Guidelines

.github/PULL_REQUEST_TEMPLATE.md, README.md, app/scripts/app.js, app/scripts/controllers.js, app/templates/apis/advanced-reference.html, app/templates/apis/authorize.html, app/templates/apis/intro.html, app/templates/apis/submit-your-app.html, app/templates/docs/card.html, app/templates/docs/organization.html, app/templates/docs/webhook.html, app/templates/power-ups.html, app/templates/power-ups/capabilities.html, app/templates/power-ups/client-library.html, app/templates/power-ups/guidelines.html
Trying to take care of outstanding open issues. Mostly updating documentation with clarifying information.
https://github.com/trello/api-docs/issues/53
https://github.com/trello/api-docs/issues/51
https://github.com/trello/api-docs/issues/50
=> Updating Documentation

app/templates/power-ups/guidelines.html
Be clear in Power-Up guiding principles that Power-Ups should stand on their own, and work where Trello does.
=> Added more guiding principles

app/templates/power-ups/client-library.html
Clarify how/when `t.navigate` and `t.showCard` should be used.
=> Usage warnings for new handlers

app/templates/power-ups/topics.html
Adding a bit of info regarding storing data at the organization scope.
This was in the glitch project comments, but not the docs.
=> Adding Info About Organization Scope

app/templates/docs/action.html, app/templates/docs/board.html, app/templates/docs/card.html, app/templates/docs/checklist.html, app/templates/docs/list.html, app/templates/docs/member.html, app/templates/docs/organization.html, app/templates/docs/token.html, app/templates/docs/type.html
Based on: https://github.com/trello/api-docs/pull/95. Going through and fixing the example code on all pages so that it is nested properly and hides when loading. Also adding syntax highlighting.
=> Fixing Examples Not Hiding

app/index.html
We should probably make this dynamic, but this at least corrects it for now!
=> Change copyright date to 2017

app/templates/power-ups/guidelines.html
Updating guidelines with restrictions on naming Power-Ups.
=> Adding Naming Restrictions

app/templates/docs/card.html, app/templates/power-ups/client-library.html
We've added new capabilities to client library as requested here: https://github.com/trello/api-docs/issues/81.
Additionally, adding documentation around need for using ISO dates: https://github.com/trello/api-docs/issues/107
https://github.com/trello/api-docs/issues/107
https://github.com/trello/api-docs/issues/81
=> Documenting ISO Dates & New Power-Up Capabilities

app/scripts/controllers.js
Adding a new community project!
=> Adding JsonToXL Project

app/templates/docs/card.html
Adding a bit more information around working with the attachments API. We've had a number of questions arise including those on this issue: https://github.com/trello/api-docs/issues/111.
Hoping that the Glitch project can be a repository for examples of how best to work with this endpoint as it is quite complicated but very powerful.
=> Improving Attachments Info

app/templates/power-ups/topics.html
Accidentally removed stuff about timeouts in previous PR: https://github.com/trello/api-docs/commit/1d814dc5f3d587e6e910b8433e8dd2a7cc60269f
=> Re-adding Timeouts Info

app/templates/power-ups/capabilities.html
=> fix typo in power-up capabilities

app/templates/apis/submit-your-app.html, app/templates/power-ups/guidelines.html, app/templates/power-ups/intro.html
Update review guidelines and make it clearer how to actually submit a Power-Up.
=> Update review guidelines.

app/templates/docs/member.html
Removing duplicate `status` property
N/A
N/A
=> Removing duplicate `status` property

app/templates/power-ups/capabilities.html
A list of the issues the PR addresses:
issue |
----- |
[github.com/trello/api-docs/issues/134](github.com/trello/api-docs/issues/134) |
A screenshot of the changes.
=> attempt to fix trello/api-docs#134

app/templates/power-ups/topics.html
https://github.com/trello/api-docs/issues/127#issuecomment-315394344
=> Add Try For t.authorize
